version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: tododb
            MYSQL_USER: todo
            MYSQL_PASSWORD: odot

    todo:
        image: com.gmail.lnqhien/todo
        restart: always
        depends_on:
            - db
        ports:
            - "8080:8080"

volumes:
    dbdata:
